unbind C-b
set-option -g prefix C-a
bind-key C-e send-prefix

set-option -g default-shell /bin/zsh
set -g        set-clipboard on
set -g default-terminal "tmux-256color"
set -as terminal-features ',*:RGB'
set -as terminal-features ',*:usstyle'
set -s        escape-time 0
set -g        renumber-windows on
set -g        base-index 1
set -g        set-titles on
set -g        set-titles-string "#{session_name}: #{window_name}"
set -g        mouse on

set -g        status on
set -g        status-interval 1
set -g        status-justify left
set -g        status-position bottom
set -g        status-left-length 100
set -g        status-right-length 100
source-file ~/.tmux.vague-theme.conf


bind o copy-mode
unbind -T copy-mode Enter
bind -T copy-mode Enter send-keys -X copy-selection
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe 'wl-copy'

bind "v" split-window -v
bind "h" split-window -h

bind r run-shell "tmux source ~/.tmux.conf"

bind - run-shell "~/dotfiles/scripts/time-tracking"

bind g run-shell "code ."
bind y new-window "~/dotfiles/scripts/fzf-zathura"

# bind k split-window -v "make; exec $SHELL"

bind w new-window "rmpc"
bind i new-window "iamb"

bind-key -r C-t run-shell "sessions"
bind-key -r t run-shell "sessions"

bind-key -r l run-shell "sessions -p"
bind-key -r C-l run-shell "sessions -p"

bind C-n new-window "nvim"

bind -n "M-/" select-window -t "1"
bind -n "M-(" select-window -t "2"
bind -n "M-[" select-window -t "3"
bind -n "M-{" select-window -t "4"
bind -n "M-'" select-window -t "5"
